### ISSUE TITLE
"Generate random" button is not generating random stack, linked list and hash table.

### ISSUE THREAD

**Issue by ghost** [tobinatore/algovis#6] opened 2021-04-30 19:51 UTC

**Comment by tobinatore** [comment] 2021-04-30 20:30
I cannot reproduce this issue for the stack. Clicking on "Generate random stack" works on my end. Are there any error messages in the console?

I fixed the issue with linked lists was fixed in 0f21756, so that should work now.

As for hash tables, the button is for generating a new empty hashtable, currently there is no functionality to randomly generate a filled one.

**Comment by ghost** [comment] 2021-05-01 06:19
> I cannot reproduce this issue for the stack. Clicking on "Generate random stack" works on my end. Are there any error messages in the console?

I tried this on different browsers and it is not generating random stack in Firefox only.

![Screenshot (105)](https://user-images.githubusercontent.com/83466458/116773451-0cf0ca00-aa73-11eb-990a-1f80189b337d.png)



> As for hash tables, the button is for generating a new empty hashtable, currently there is no functionality to randomly generate a filled one.


In case of hash table, neither the page loaded with default hash table nor the button generating new empty hash in Firefox only.


![Screenshot (106)](https://user-images.githubusercontent.com/83466458/116773700-9ce34380-aa74-11eb-928c-7762cc8cb68a.png)

**Comment by tobinatore** [comment] 2021-05-03 09:26
Ahh, I got it. Firefox does not support private fields... This should be an easy fix.

**Closed as completed** 2021-05-03 09:30 UTC
